version: '3'

volumes:
  kittygram_production:
  static_volume:
  media:

services:
  kittygram:
    image: postgres:13.10
    env_file: .env
    volumes:
      - kittygram_production:/var/lib/postgresql/data
  backend:
    image: mccloudin/kitty_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media:/app/media/
  frontend:
    image: mccloudin/kitty_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/static
  gateway:
    image: mccloudin/kitty_nginx
    env_file: .env
    volumes:
      - static_volume:/static/
      - media:/app/media/
    ports:
      - 9000:80
